type FeatureToggleObjectType {
  name: String!
  isControlled: Boolean!
  isEnabled: Boolean!
}

type Query {
  getAllFeatureToggles: [FeatureToggleObjectType!]!
}

type Mutation {
  upsertFeatureToggle(payload: UpsertFeatureToggleInputType!): FeatureToggleObjectType!
}

input UpsertFeatureToggleInputType {
  name: String
  isControlled: Boolean
  isEnabled: Boolean
}

type Subscription {
  featureToggleUpserted: FeatureToggleObjectType!
}